version: "2"

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - unused
    - revive
    - errcheck
    - gosec
    - ineffassign
    - misspell
    - unconvert

formatters:
  enable:
    - gofmt
    - goimports
